# Interval in seconds between checking attempts. Note that Spiget.org caches results for up to 20 minutes.
# Type: Integer
# Default: 60
interval: 60

# Minimum delay in milliseconds between Spiget.org requests. Every plugin causes 3 HTTP requests.
# Type: Integer
# Default: 1000
minimum-delay-between-spiget-requests: 1000

# Whether to announce updates for new plugins.
# A plugin is considered new if it doesn't have a "version" set it in plugins.yml.
# Type: boolean
# Default: false
announce-new-plugins: false
